name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
    build-publish:
        runs-on: ubuntu-latest

        steps:

          - uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '18'
    
          - name: Install the dependencies
            run: npm i
    
          - name: Install vsce
            run: npm i -g vsce
    
          - name: Publish
            run: |
              export VSCE_STORE=file
              vsce login WangQin ${{ secrets.AZURE_MARKETPLACE_ACCESS_TOKEN }}
            env:
              AZURE_MARKETPLACE_ACCESS_TOKEN: ${{ secrets.AZURE_MARKETPLACE_ACCESS_TOKEN }}
